version: '3.8'

services:
  app:
    container_name: front_ecommerce_liz
    image: front_ecommerce_liz
    build:
      context: ./frontend/loja-liz
    ports:
      - 8080:80
    deploy:
      resources:
        limits:
          memory: 2G
