
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ '192.168.3.2:9090' ]

  - job_name: 'web-api'
    scrape_interval: 5s
    static_configs:
      - targets: [ '192.168.3.2:5075' ]


#  - job_name: cadvisor
#    scrape_interval: 5s
#    static_configs:
#      - targets:
#          - cadvisor:8080